spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.data.mongodb.uri=mongodb://localhost:27017/analytics_dashboard
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update